- name: Install plex-mpv-shim from pip as user package
  pip:
    name: plex-mpv-shim
    state: latest
    extra_args: --user

- name: Install pystray from pip as user package
  pip:
    name: pystray
    state: latest
    extra_args: --user

- name: Install python3-tk
  become: yes
  apt:
    name: python3-tk
    state: present

- name: Install libmpv1
  become: yes
  apt:
    name: libmpv1
    state: present
