- name: Set up local machine
  hosts: "{{ host }}"
  roles:
    - { role: grub, tags: ["grub"] }
    - { role: snap, tags: ["snap"] }
    - { role: apt, tags: ["apt"] }
    - { role: bin, tags: ["bin"] }
    - { role: linux, tags: ["linux"] }
    - { role: profile, tags: ["profile"] }
    - { role: ssh, tags: ["ssh"] }
    - { role: python, tags: ["python"] }
    - { role: pipx, tags: ["pipx"] }
    - { role: dotfiles, tags: ["dotfiles"] }
    - { role: fish, tags: ["fish"] }
    - { role: fonts, tags: ["fonts"] }
    - { role: gnome, tags: ["gnome"] }
    - { role: sway, tags: ["sway"] }
    - { role: xdg, tags: ["xdg"] }
    - { role: git, tags: ["git"] }
    - { role: vim, tags: ["vim"] }
    - { role: sublime, tags: ["sublime"] }
    - { role: google-chrome, tags: ["google-chrome"] }
    - { role: jetbrains, tags: ["jetbrains"] }
    - { role: zsa, tags: ["zsa"] }
    - { role: docker, tags: ["docker"] }
    - role: fubarhouse.golang
      tags: ["go"]
      go_version: 1.22.1
      GOPATH: /home/will/go
      become: yes
    # - { role: blackd, tags: ["blackd"] }
    - { role: syncthing, tags: ["syncthing"] }
    - { role: wayland-tweaks, tags: ["wayland-tweaks"] }
    # - { role: plex-mpv, tags: ["plex-mpv"] }
    # - { role: rust, tags: ["rust"] }

- name: Set up autofs on some machines
  hosts: ["dux", "victor"]
  roles:
    - { role: autofs, tags: ["autofs"] }
