- name: Set up local machine
  hosts: "{{ host }}"
  roles:
    - { role: linux, tags: ["linux"] }
    - { role: fish, tags: ["fish"] }
    - { role: fonts, tags: ["fonts"] }
    - { role: gnome, tags: ["gnome"] }
    - { role: regolith, tags: ["regolith"] }
    - { role: git, tags: ["git"] }
    - { role: node, tags: ["node"] }
    - { role: vim, tags: ["vim"] }
    - { role: sublime, tags: ["sublime"] }
    - { role: google-chrome, tags: ["google-chrome"] }
    - { role: zsa, tags: ["zsa"] }
