- name: Install pipx
  become: yes
  apt:
    name: pipx
    state: present

- name: Install or upgrade pipx packages
  loop: "{{ pipx_packages }}"
  community.general.pipx:
    name: "{{ item.name }}"
    state: "{{ item.state if item.state is defined else 'latest' }}"
    python: "{{ item.python if item.python is defined else 'python3' }}"
