- name: Run misc tasks
  include_tasks: misc.yml

- name: "Check if {{ item.pkg }} {{ item.version }} is installed"
  set_fact:
    package_installed: "{{ item.pkg in ansible_facts.packages }}"

- name: "Get installed {{ item.pkg }} version"
  set_fact:
    package_version: "{{ ansible_facts.packages[item.pkg][0].version }}"
  when: package_installed and item.version is defined

- name: "Decide if we should install {{ item.pkg }} {{ item.version }}"
  set_fact:
    should_install: >-
      {{ 
        ( not package_installed ) 
        or 
        (
          package_installed and
          package_version is defined 
          and item.version is defined 
          and package_version|default('undefined') != item.version
        ) 
      }}

- name: "Download {{ item.pkg }} {{ item.version }} deb file"
  when: should_install
  get_url:
    url: "{{ item.url }}"
    dest: "/tmp/{{ item.pkg }}-{{ item.version }}.deb"

- name: "Install {{ item.pkg }} {{ item.version }}"
  when: should_install
  become: yes
  command: dpkg -i "/tmp/{{ item.pkg }}-{{ item.version }}.deb"
