- name: Add an apt signing key for {{ item.name }}
  when: item.key is defined
  become: yes
  apt_key:
    url: "{{ item.key }}"
    state: present

- name: Add apt repo for {{ item.name }}
  become: yes
  apt_repository:
    repo: deb http://archive.canonical.com/ubuntu hardy partner
    state: present
    update_cache: no
    filename: "{{ item.name }}"
  notify: Update apt packages
