ZSH=$HOME/.oh-my-zsh
ZSH_THEME="fishy"
alias lua="nocorrect lua"
alias npm='nocorrect npm'
alias sv='sudo vim'
alias sre='screen -rS'
alias sls='screen -list'
alias cal='gcalcli'

plugins=(git screen urltools django)
source $ZSH/oh-my-zsh.sh

alias apt-get='sudo apt-get'
alias ram="free -l -t"

export LC_ALL=en_GB.utf-8
export LANG="$LC_ALL"
export LANGUAGE="$LC_ALL"


