# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

"notion"=""
"alacritty" = ""
"home assistant"="󰟐"
"github" = ""
"gitlab" = ""
"google meet"="󰻒"
"google docs" = "󰈙"
"evidenced" = "󱈹"
"excalidraw" = "󰔙"
"stack overflow" = "󰓌"
"google" = "󰊭"
"jira"="󰌃"
"reddit"="󰑍"
"youtube"="󰗃"
"plex"="󰚺"
"datadog"="󰩄"
"meet "="󰻒"
"calendar"="󰃭"
"hacker news"=""
"private browsing" = "󰗹"
"firefox" = ""
"zen browser" = ""
"libreoffice calc" = ""
"libreoffice writer" = ""
"libreoffice" = ""
"vim" = ""
"menu" = ""
"calculator" = "󰃬"
"speedcrunch" = "󰃬"
"videostream" = ""
"mpv" = ""
"music" = ""
"disk usage" = ""
".pdf" = ""
"spotify" = "󰓇"
"psst-gui" = "󰓇"
"foot" = ""
"gnome-terminal-server"="󰆍"
"ghostty"="󰆍"
"sublime_text" = ""
"pavucontrol" = "󰕾"
"ulauncher" = "▼"
"code" = "󰨞"
"cursor" = "󰋘"
"nemo" = "󰉋"
"file-roller" = "󰀼"
"sublime_merge" = ""
"jetbrains-pycharm" = "󰌠"
"jetbrains-goland" = ""
"jetbrains-webstorm" = ""
"eog" = "󰋩"
"nomacs" = "󰋩"
"software" = ""
"gnome-power-statistics"="󰁾"
"audacity"=""
"gimp"=""
"inkscape"="󰀁"
"youtube"=""
"obsidian"="󰮋"
"printer"="󰐪"
"steam"="󰓓"
"slack"="󰒱"
"subsurface"="󰷄"
"meld"="󰽜"
"seahorse"="󱕴"
"gedit"="󰭸"
"virtual machine"="󰒋"
"qemu"="󱄄"
"csv"=""
"1password"="󰢁"
"blueman-manager"="󰂯"
"jetbrains-toolbox"="󰆦"
"aws vpn client"="󰖂"
"heroic"="󱢾"
"disks"="󰋊"
"godot"=""
"zoom"="󰻒"
"factorio"="󰈏"
"openttd"=""
"copyq"=""
"kdenlive"=""
"discord"=""
"chrome"=""
"chromium"=""
"balena-etcher"=""
"loomish"="󰨜"
"balena-etcher"="󱊞"
"text editor"="󱩼"
"firmware-updater"=""
"logseq"="󰉺"
"bitwarden"=""
"bruno"="󰩃"
"postman"="󰙃"
"calibre"="󱉟"
"super productivity"=""
"wayland output mirror"=""
"qgis"=""
"bottles"="󰡔"
"popup-term"="󰄛"
"limo"="L"
"characters"="󱁯"
"kerbal space program"=""
"todoist"=""
"fastmail"="󰇮"
"helium"=""
"grayjay"="󱗆"
"picture-in-picture"="󰹗"
"zed"="󰬡"
[other]
fallback_icon = "🤨"
deduplicate_icons = false
