- name: Set inotify limit
  become: yes
  sysctl:
    name: fs.inotify.max_user_watches
    value: 524288
    state: present

- name: Set default editor to vim
  become: yes
  alternatives:
    name: editor
    path: /usr/bin/vim

- name: Ensure en_GB exists
  locale_gen:
    name: en_GB.UTF-8
    state: present
