- block:
    - name: Set inotify limit
      include_role:
        name: gantsign.inotify
      vars:
        inotify_max_user_watches: 100000
  become: yes

- name: Set default editor to vim
  become: yes
  alternatives:
    name: editor
    path: /usr/bin/vim
