- block:
    - name: Set inotify limit
      include_role:
        name: gantsign.inotify
      vars:
        inotify_max_user_watches: 100000
  become: yes

- name: Install apt packages
  become: yes
  apt: name={{ apt_packages }} state=present



