- name: Install deadsnakes repo
  become: yes
  apt_repository:
    repo: "ppa:deadsnakes/ppa"
  register: apt_repo

- name: Install python
  become: yes
  apt:
    name:
      - python3
      - python3-pip
      - python3-dev
      - python3.8
      - python3.8-dev
      - python3.8-distutils
      - python3.9
      - python3.9-dev
      - python3.9-distutils
      - python3.10
      - python3.10-dev
      - python3.10-distutils
      - python3.11
      - python3.11-dev
      - python3.11-distutils
      - python3.12
      - python3.12-dev
      # - python3.12-distutils # Does not exist
      - python-is-python3
    state: present

- name: Check if poetry is installed
  stat:
    path: "{{ dotfiles_user_home }}/.local/bin/poetry"
  register: poetry_bin
  changed_when: false

- name: Install poetry
  when: not poetry_bin.stat.exists
  args:
    executable: /usr/bin/bash
  shell: |
    set -o pipefail &&
    curl -sSL https://install.python-poetry.org | python -
