- name: Update Xresources
  template:
    src: "Xresources.j2"
    dest: "{{ dotfiles_user_home }}/.config/regolith/Xresources"
    mode: 0664
  notify: Restart i3

- name: Update i3status
  template:
    src: "i3status.j2"
    dest: "{{ dotfiles_user_home }}/.config/i3status/config"
    mode: 0664
  notify: Restart i3
