- name: Modify Obsidian .desktop file to launch in Wayland mode
  lineinfile:
    path: /var/lib/snapd/desktop/applications/obsidian_obsidian.desktop
    regexp: "^Exec="
    line: "Exec=env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/obsidian_obsidian.desktop /snap/bin/obsidian %U"
    state: present
    backup: yes
  become: yes
