- name: Modify Obsidian .desktop file to launch in Wayland mode
  lineinfile:
    path: /usr/share/applications/obsidian.desktop
    regexp: '^Exec='
    line: 'Exec=env OBSIDIAN_USE_WAYLAND=1 obsidian %U'
    state: present
    backup: yes
  become: yes
