- name: Check if code.desktop file exists
  stat:
    path: /usr/share/applications/code.desktop
  register: vscode_desktop_file

- name: Modify vscode .desktop file to launch in Wayland mode
  lineinfile:
    path: /usr/share/applications/code.desktop
    regexp: "^Exec=/usr/share/code/code"
    line: "Exec=env GDK_BACKEND=wayland /usr/share/code/code --unity-launch %F --ozone-platform=wayland --enable-features=UseOzonePlatform,WebRTCPipeWireCapturer %U"
    state: present
    backup: yes
  become: yes
  when: vscode_desktop_file.stat.exists

- name: Modify vscode .desktop file for new window to launch in Wayland mode
  lineinfile:
    path: /usr/share/applications/code.desktop
    regexp: "^Exec=/usr/share/code/code --new-window"
    line: "Exec=env GDK_BACKEND=wayland /usr/share/code/code --new-window %F --ozone-platform=wayland --enable-features=UseOzonePlatform,WebRTCPipeWireCapturer %U"
    state: present
    backup: yes
  become: yes
  when: vscode_desktop_file.stat.exists
