- name: Create terminal profile
  loop:
    - key: "{{terminal_dconf_path}}/profiles:/default"
      value: "'{{terminal_profile}}'"
    - key: "{{terminal_dconf_path}}/profiles:/list"
      value: "['{{terminal_profile}}']"
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"

- name: Setup terminal profile
  loop:
    - key: "visible-name"
      value: "'wjdp'"
    - key: "foreground-color"
      value: "'rgb(243,243,243)'"
    - key: "palette"
      value: "['rgb(0,0,0)', 'rgb(205,0,0)', 'rgb(0,205,0)', 'rgb(205,205,0)', 'rgb(30,144,255)', 'rgb(205,0,205)', 'rgb(0,205,205)', 'rgb(229,229,229)', 'rgb(76,76,76)', 'rgb(255,0,0)', 'rgb(0,255,0)', 'rgb(255,255,0)', 'rgb(70,130,180)', 'rgb(255,0,255)', 'rgb(0,255,255)', 'rgb(255,255,255)']"
    - key: cursor-shape
      value: "'block'"
    - key: use-system-font
      value: "false"
    - key: use-theme-colors
      value: "false"
    - key: use-transparent-background
      value: "true"
    - key: background-transparency-percent
      value: "4"
    - key: font
      value: "'JetBrains Mono 12'"
    - key: cell-height-scale
      value: "1.05"
    - key: use-theme-transparency
      value: "false"
    - key: bold-color-same-as-fg
      value: "false"
    - key: bold-color
      value: "'rgb(255,255,255)'"
    - key: background-color
      value: "'rgb(7,7,8)'"
    - key: background-transparency-percent
      value: "0"
    - key: scrollbar-policy
      value: "'never'"
  dconf:
    key: "{{terminal_dconf_path}}/profiles:/:{{terminal_profile}}/{{ item.key }}"
    value: "{{ item.value }}"
