- name: Install git
  apt: name=git state=present
  become: yes

- name: Install git-lfs
  apt: name=git-lfs state=present
  become: yes

- name: Link global gitignore file
  file:
    src: "{{ dotfiles_home }}/roles/git/files/gitignore_global.link"
    dest: "{{ dotfiles_user_home }}/.gitignore_global"
    state: link
    force: yes

- name: Link gitattributes file
  file:
    src: "{{ dotfiles_home }}/roles/git/files/gitattributes_global.link"
    dest: "{{ dotfiles_user_home }}/.gitattributes_global"
    state: link
    force: yes

- name: Update gitconfig
  template:
    src: "gitconfig.j2"
    dest: "{{ dotfiles_user_home }}/.gitconfig"
    mode: 0664
