- name: Link waybar config
  file:
    src: "{{ dotfiles_home }}/roles/sway/files/waybar"
    dest: "{{ dotfiles_user_home }}/.config/waybar"
    state: link
    force: yes

- name: Update waybar config file from template
  template:
    src: "waybar.j2"
    dest: "{{ dotfiles_user_home }}/.config/waybar/config"
    mode: 0664

- name: Pull and build workstyle from cargo
  community.general.cargo:
    name: workstyle

- name: Ensure workstyle config directory exists
  file:
    path: "{{ dotfiles_user_home }}/.config/workstyle"
    state: directory
    mode: 0775

- name: Link workstyle config
  file:
    src: "{{ dotfiles_home }}/roles/sway/files/workstyle.toml"
    dest: "{{ dotfiles_user_home }}/.config/workstyle/config.toml"
    state: link
    force: yes
