- name: Add repos
  loop: "{{ sway_apt_repos }}"
  become: yes
  apt_repository:
    repo: "{{ item }}"
    state: present

- name: Install apt packages
  become: yes
  apt: name={{ sway_apt_packages }} state=present

- name: Link fdfind to fd
  become: yes
  file:
    src: "/usr/bin/fdfind"
    dest: "/usr/bin/fd"
    state: link
    force: yes

- name: Ensure directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
  loop:
    - "{{ dotfiles_user_home }}/.config/sway"
    - "{{ dotfiles_user_home }}/.config/workstyle"

- name: Link sway config
  file:
    src: "{{ dotfiles_home }}/roles/sway/files/config"
    dest: "{{ dotfiles_user_home }}/.config/sway/config"
    state: link
    force: yes

- name: Link sway config.d
  file:
    src: "{{ dotfiles_home }}/roles/sway/files/config.d"
    dest: "{{ dotfiles_user_home }}/.config/sway/config.d"
    state: link
    force: yes

- name: Link workstyle config
  file:
    src: "{{ dotfiles_home }}/roles/sway/files/workstyle.toml"
    dest: "{{ dotfiles_user_home }}/.config/workstyle/config.toml"
    state: link
    force: yes

- name: Link waybar config
  file:
    src: "{{ dotfiles_home }}/roles/sway/files/waybar"
    dest: "{{ dotfiles_user_home }}/.config/waybar"
    state: link
    force: yes

- name: Update output config
  template:
    src: "outputs.j2"
    dest: "{{ dotfiles_user_home }}/.config/sway/config.d/05-outputs"
    mode: 0664
