- name: Include sway tasks
  include_tasks: "{{ task }}"
  loop_control:
    loop_var: task
  loop:
    - apt.yml
    - sway.yml
    - bar.yml
    - backlight.yml
    - mako.yml
    - launcher.yml
    - wofi.yml
    - kanshi.yml
    - reboot-windows.yml
