- name: Show GRUB menu for a fixed time
  become: yes
  lineinfile:
    dest: /etc/default/grub
    regexp: '^GRUB_TIMEOUT='
    line: 'GRUB_TIMEOUT=5'
    state: present
  notify: Update GRUB

- name: Set GRUB timeout style to menu
  become: yes
  lineinfile:
    dest: /etc/default/grub
    regexp: '^GRUB_TIMEOUT_STYLE='
    line: 'GRUB_TIMEOUT_STYLE=menu'
    state: present
  notify: Update GRUB
